engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: PSR1
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: ""

ratings:
  paths:
    - "**.php"

exlude_paths:
  - "vendor/"
