engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: PSR1
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: "cleancode,codesize,controversial,design,naming,unusedcode"
    checks:
      CleanCode/StaticAccess:
        properties:
          exceptions: "Variable"
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false

ratings:
  paths:
    - "**.php"

exlude_paths:
  - "vendor/"
