filter:
  excluded_paths:
    - vendor/*

checks:
  php: true

coding_style:
  php: { }

build:
  environment:
    php:
      version: 7.1.0
    tests:
      override:
        - command: 'phpunit'
          coverage:
            file: 'build/logs/clover.xml'
            format: 'clover'
