language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - COVERAGE_VERSION=7.1
    - PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH
  matrix:
    - PHP_VERSION: 7.0
      XDEBUG_VC_VERSION: 14
    - PHP_VERSION: 7.1
      XDEBUG_VC_VERSION: 14
    - PHP_VERSION: 7.2
      XDEBUG_VC_VERSION: 14

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

git:
  depth: 1

branches:
  only:
    - master

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update --classmap-authoritative --no-interaction --no-progress --no-suggest --prefer-dist
before_script:
  - function coverage() { test $TRAVIS_PHP_VERSION = $COVERAGE_VERSION; }
script:
  - coverage && phpunit || phpunit --no-coverage
after_success:
  - coverage && travis_retry ocular code-coverage:upload --format=php-clover build/logs/clover.xml
  - coverage && travis_retry test-reporter --no-interaction
  - coverage && travis_retry coveralls --no-interaction
