language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  global:
    - COVERAGE_VERSION=7.1
    - PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

git:
  depth: 1

branches:
  only:
    - master

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update --classmap-authoritative --no-interaction --no-progress --no-suggest --prefer-dist
script:
  - test $TRAVIS_PHP_VERSION = $COVERAGE_VERSION && phpunit || phpunit --no-coverage
after_success:
  - test $TRAVIS_PHP_VERSION = $COVERAGE_VERSION && bash resources/travis-ci/after_success.bash
