language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  global:
    - COVERAGE=--no-coverage
    - PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH

os:
  - linux
  - osx

matrix:
  allow_failures:
    - php: nightly
    - os: osx
  fast_finish: true

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update --classmap-authoritative --no-interaction --no-progress --no-suggest --prefer-dist
script:
  - phpunit $COVERAGE
